INSERT INTO link (link_date, link_embed, link_description) VALUES (
    '2024-02-01',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@fechinfresheggs/video/7300163529347190048" data-video-id="7300163529347190048" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@fechinfresheggs" href="https://www.tiktok.com/@fechinfresheggs?refer=embed">@fechinfresheggs</a> Mr fox decided to mess up my marriage proposal and attack my chicken word Will 🦊💥 <a title="fyp" target="_blank" href="https://www.tiktok.com/tag/fyp?refer=embed">#fyp</a> <a title="forgoupage" target="_blank" href="https://www.tiktok.com/tag/forgoupage?refer=embed">#forgoupage</a> <a title="viral" target="_blank" href="https://www.tiktok.com/tag/viral?refer=embed">#viral</a> <a title="chickensoftiktok" target="_blank" href="https://www.tiktok.com/tag/chickensoftiktok?refer=embed">#chickensoftiktok</a> <a title="mothernature" target="_blank" href="https://www.tiktok.com/tag/mothernature?refer=embed">#mothernature</a> <a title="proposal" target="_blank" href="https://www.tiktok.com/tag/proposal?refer=embed">#proposal</a> <a title="homesteadlife" target="_blank" href="https://www.tiktok.com/tag/homesteadlife?refer=embed">#homesteadlife</a> <a title="foxy" target="_blank" href="https://www.tiktok.com/tag/foxy?refer=embed">#foxy</a> <a title="fail" target="_blank" href="https://www.tiktok.com/tag/fail?refer=embed">#fail</a> <a target="_blank" title="♬ Just How You Like It - K.A.D &#38; Kak Hatt" href="https://www.tiktok.com/music/Just-How-You-Like-It-6914598762905683970?refer=embed">♬ Just How You Like It - K.A.D &#38; Kak Hatt</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Смотри, как лисичка предложение портит... наверное потому что оно не ей 🥺'
), (
    '2024-02-02',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@arayushkaaa1/video/7304634672619785477" data-video-id="7304634672619785477" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@arayushkaaa1" href="https://www.tiktok.com/@arayushkaaa1?refer=embed">@arayushkaaa1</a> @kerd ❤️‍🩹<a title="вальсвыпускников" target="_blank" href="https://www.tiktok.com/tag/%D0%B2%D0%B0%D0%BB%D1%8C%D1%81%D0%B2%D1%8B%D0%BF%D1%83%D1%81%D0%BA%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2?refer=embed">#вальсвыпускников</a> <a title="rec" target="_blank" href="https://www.tiktok.com/tag/rec?refer=embed">#rec</a> <a title="11класс" target="_blank" href="https://www.tiktok.com/tag/11%D0%BA%D0%BB%D0%B0%D1%81%D1%81?refer=embed">#11класс</a> <a target="_blank" title="♬ original sound - ✬ - Kairo Vlogs" href="https://www.tiktok.com/music/original-sound-✬-7257846221934054149?refer=embed">♬ original sound - ✬ - Kairo Vlogs</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Через пол года у нас свадьба 😍 так что можно тебя пригласить на свадебный танец? 🤭'
), (
    '2024-02-03',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@yummy_maki/video/7301274805423082757" data-video-id="7301274805423082757" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@yummy_maki" href="https://www.tiktok.com/@yummy_maki?refer=embed">@yummy_maki</a> <a title="yummymaki" target="_blank" href="https://www.tiktok.com/tag/yummymaki?refer=embed">#yummymaki</a> <a title="yummy" target="_blank" href="https://www.tiktok.com/tag/yummy?refer=embed">#yummy</a> <a title="сушироллы" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D1%83%D1%88%D0%B8%D1%80%D0%BE%D0%BB%D0%BB%D1%8B?refer=embed">#сушироллы</a> <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="рекомендации" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8?refer=embed">#рекомендации</a> <a title="тренды" target="_blank" href="https://www.tiktok.com/tag/%D1%82%D1%80%D0%B5%D0%BD%D0%B4%D1%8B?refer=embed">#тренды</a> <a title="пустойквадраттусклойцвет🌞" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D1%83%D1%81%D1%82%D0%BE%D0%B9%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D1%82%D1%83%D1%81%D0%BA%D0%BB%D0%BE%D0%B9%D1%86%D0%B2%D0%B5%D1%82%F0%9F%8C%9E?refer=embed">#пустойквадраттусклойцвет🌞</a> <a target="_blank" title="♬ оригинальный звук - yummy_maki" href="https://www.tiktok.com/music/оригинальный-звук-7301274822173133574?refer=embed">♬ оригинальный звук - yummy_maki</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Приглашаю тебя поесть суши вместе 😋'
), (
    '2024-02-04',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@sharkblanket.kz1/video/7306036604840283398" data-video-id="7306036604840283398" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@sharkblanket.kz1" href="https://www.tiktok.com/@sharkblanket.kz1?refer=embed">@sharkblanket.kz1</a> <p>А чтобы вы смогли кормить свою акулу, заказывайте ее у нас!🥰 Всего за 17,500 тенге😍 Для заказа пишите в Директ инстаграма shark_blanket_kz (указан в профиле) </p> <a target="_blank" title="♬ Jaws Theme - Jaws" href="https://www.tiktok.com/music/Jaws-Theme-113240306?refer=embed">♬ Jaws Theme - Jaws</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Если хищник в доме, то нужно его хорошо кормить 😋 иначе он съест тебя 😬'
), (
    '2024-02-05',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mommynmetiktok/video/7306905398739471659" data-video-id="7306905398739471659" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mommynmetiktok" href="https://www.tiktok.com/@mommynmetiktok?refer=embed">@mommynmetiktok</a> Some guys just dont get it.   <a title="guysdontgetit" target="_blank" href="https://www.tiktok.com/tag/guysdontgetit?refer=embed">#guysdontgetit</a> <a title="itsthelittlethings" target="_blank" href="https://www.tiktok.com/tag/itsthelittlethings?refer=embed">#itsthelittlethings</a> <a title="chivalryisntdead" target="_blank" href="https://www.tiktok.com/tag/chivalryisntdead?refer=embed">#chivalryisntdead</a> <a title="chivalryisdead" target="_blank" href="https://www.tiktok.com/tag/chivalryisdead?refer=embed">#chivalryisdead</a> <a title="vegasbaby" target="_blank" href="https://www.tiktok.com/tag/vegasbaby?refer=embed">#vegasbaby</a> <a title="watchandlearn" target="_blank" href="https://www.tiktok.com/tag/watchandlearn?refer=embed">#watchandlearn</a> <a title="happywifehappylife" target="_blank" href="https://www.tiktok.com/tag/happywifehappylife?refer=embed">#happywifehappylife</a> <a target="_blank" title="♬ Expensive Cat food - Music For Cats" href="https://www.tiktok.com/music/Expensive-Cat-food-7109537048607868929?refer=embed">♬ Expensive Cat food - Music For Cats</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Если такие хитрецы будут постояно попадаться, то у тебя бужет бедный парень 🥺'
), (
    '2024-02-06',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@_._chloe._/video/7287454224105868577" data-video-id="7287454224105868577" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@_._chloe._" href="https://www.tiktok.com/@_._chloe._?refer=embed">@_._chloe._</a> <a title="mathboy" target="_blank" href="https://www.tiktok.com/tag/mathboy?refer=embed">#mathboy</a> <a title="literaturegirl" target="_blank" href="https://www.tiktok.com/tag/literaturegirl?refer=embed">#literaturegirl</a> <a title="boyfriend" target="_blank" href="https://www.tiktok.com/tag/boyfriend?refer=embed">#boyfriend</a> <a title="girlfreind" target="_blank" href="https://www.tiktok.com/tag/girlfreind?refer=embed">#girlfreind</a> <a target="_blank" title="♬ som original - rick" href="https://www.tiktok.com/music/som-original-7258012597130529541?refer=embed">♬ som original - rick</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Можещб рассказать мне, что вы читаете на русском и литовском... Мне будет приятно послушать 🥰'
), (
    '2024-02-07',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@.ameno.venti/video/7307704761611013383" data-video-id="7307704761611013383" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@.ameno.venti" href="https://www.tiktok.com/@.ameno.venti?refer=embed">@.ameno.venti</a> эти ваши тренды <a title="коты" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%BE%D1%82%D1%8B?refer=embed">#коты</a> <a title="отношения" target="_blank" href="https://www.tiktok.com/tag/%D0%BE%D1%82%D0%BD%D0%BE%D1%88%D0%B5%D0%BD%D0%B8%D1%8F?refer=embed">#отношения</a> <a title="recommendations" target="_blank" href="https://www.tiktok.com/tag/recommendations?refer=embed">#recommendations</a> <a title="рекомендации" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8?refer=embed">#рекомендации</a> <a title="fypシ" target="_blank" href="https://www.tiktok.com/tag/fyp%E3%82%B7?refer=embed">#fypシ</a> <a title="fyp" target="_blank" href="https://www.tiktok.com/tag/fyp?refer=embed">#fyp</a> <a title="свидание" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D0%B2%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5?refer=embed">#свидание</a> <a target="_blank" title="♬ оригинальный звук - Аmeno.boy🍃" href="https://www.tiktok.com/music/оригинальный-звук-7307704847476886274?refer=embed">♬ оригинальный звук - Аmeno.boy🍃</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Я всегда очень рад приезжать к тебе в гости ❤️'
), (
    '2024-02-08',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@madi.lynn.b/video/7302081547329408299" data-video-id="7302081547329408299" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@madi.lynn.b" href="https://www.tiktok.com/@madi.lynn.b?refer=embed">@madi.lynn.b</a> a blanket.. +him 😂🤍 <a title="boyfriend" target="_blank" href="https://www.tiktok.com/tag/boyfriend?refer=embed">#boyfriend</a> <a title="boyfriendsoftiktok" target="_blank" href="https://www.tiktok.com/tag/boyfriendsoftiktok?refer=embed">#boyfriendsoftiktok</a> <a title="fyp" target="_blank" href="https://www.tiktok.com/tag/fyp?refer=embed">#fyp</a> <a title="imcold" target="_blank" href="https://www.tiktok.com/tag/imcold?refer=embed">#imcold</a> <a target="_blank" title="♬ original sound - madi" href="https://www.tiktok.com/music/original-sound-7302081650681187115?refer=embed">♬ original sound - madi</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Смотри, я тоже так хочу греться! 🔥'
), (
    '2024-02-09',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@loswubis/video/7302132411054263558" data-video-id="7302132411054263558" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@loswubis" href="https://www.tiktok.com/@loswubis?refer=embed">@loswubis</a> La vida de los hermanitos siempre es amor odio 🤪 <a title="gatos" target="_blank" href="https://www.tiktok.com/tag/gatos?refer=embed">#gatos</a> <a title="loswubis" target="_blank" href="https://www.tiktok.com/tag/loswubis?refer=embed">#loswubis</a> <a title="gato" target="_blank" href="https://www.tiktok.com/tag/gato?refer=embed">#gato</a> <a title="gatosdetiktok" target="_blank" href="https://www.tiktok.com/tag/gatosdetiktok?refer=embed">#gatosdetiktok</a> <a title="salemelmiau" target="_blank" href="https://www.tiktok.com/tag/salemelmiau?refer=embed">#salemelmiau</a> <a title="castielelmiau" target="_blank" href="https://www.tiktok.com/tag/castielelmiau?refer=embed">#castielelmiau</a> <a title="gatostiktok" target="_blank" href="https://www.tiktok.com/tag/gatostiktok?refer=embed">#gatostiktok</a> <a title="gatitostiktok" target="_blank" href="https://www.tiktok.com/tag/gatitostiktok?refer=embed">#gatitostiktok</a> <a title="miaumiau🐈" target="_blank" href="https://www.tiktok.com/tag/miaumiau%F0%9F%90%88?refer=embed">#miaumiau🐈</a> <a title="gatitos" target="_blank" href="https://www.tiktok.com/tag/gatitos?refer=embed">#gatitos</a> <a target="_blank" title="♬ sonido original - Los wubis" href="https://www.tiktok.com/music/sonido-original-7302132433180363526?refer=embed">♬ sonido original - Los wubis</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Опять видео с нами слили в интернет 🙄'
), (
    '2024-02-10',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@sharkyy_.3711/video/7305121205458144542" data-video-id="7305121205458144542" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@sharkyy_.3711" href="https://www.tiktok.com/@sharkyy_.3711?refer=embed">@sharkyy_.3711</a> @⭐️🇲🇽_ARI_🇲🇽⭐️ <a target="_blank" title="♬ original sound - _.Blake._" href="https://www.tiktok.com/music/original-sound-7305121246277077790?refer=embed">♬ original sound - _.Blake._</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'А ты самая сладкая мяу ❤️'
), (
    '2024-02-11',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@aldaaaria/video/7305156959513152770" data-video-id="7305156959513152770" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@aldaaaria" href="https://www.tiktok.com/@aldaaaria?refer=embed">@aldaaaria</a> Не рекомендую, не ставлю лайк 🤡 <a title="свидание" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D0%B2%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5?refer=embed">#свидание</a> <a title="свидания" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D0%B2%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F?refer=embed">#свидания</a> <a title="идеядлясвидания" target="_blank" href="https://www.tiktok.com/tag/%D0%B8%D0%B4%D0%B5%D1%8F%D0%B4%D0%BB%D1%8F%D1%81%D0%B2%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F?refer=embed">#идеядлясвидания</a> <a title="батуми" target="_blank" href="https://www.tiktok.com/tag/%D0%B1%D0%B0%D1%82%D1%83%D0%BC%D0%B8?refer=embed">#батуми</a> <a title="грузия" target="_blank" href="https://www.tiktok.com/tag/%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%8F?refer=embed">#грузия</a> <a target="_blank" title="♬ оригинальный звук - aldaaria" href="https://www.tiktok.com/music/оригинальный-звук-7305157163402464002?refer=embed">♬ оригинальный звук - aldaaria</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Пойдём с тобой на такое свидание? 😂 Дума. нам будет очень интересно 😈'
), (
    '2024-02-12',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@lourenco_copeto/video/7304363553786432800" data-video-id="7304363553786432800" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@lourenco_copeto" href="https://www.tiktok.com/@lourenco_copeto?refer=embed">@lourenco_copeto</a> <p>Real life painting 🎨☀️🌱🌼🐝</p> <a target="_blank" title="♬ original sound - Speedy" href="https://www.tiktok.com/music/original-sound-7265811431315032864?refer=embed">♬ original sound - Speedy</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Хочу с тобой также ❤️ Сидеть вдвоём, где никого в радиусе километра нету, да ещё и с прекрасным видем 😍'
), (
    '2024-02-13',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@v_vistavia/video/7312853317162503429" data-video-id="7312853317162503429" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@v_vistavia" href="https://www.tiktok.com/@v_vistavia?refer=embed">@v_vistavia</a> Навсегда останутся теплые воспоминания, фотографии, а ещё ленточки от букетов 🎀 Цветы не вечны, как и жизни людей, но это не делает их бесполезными. <a title="цветы" target="_blank" href="https://www.tiktok.com/tag/%D1%86%D0%B2%D0%B5%D1%82%D1%8B?refer=embed">#цветы</a> <a title="подарок" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%BE%D0%B4%D0%B0%D1%80%D0%BE%D0%BA?refer=embed">#подарок</a> <a title="цветыбукеты" target="_blank" href="https://www.tiktok.com/tag/%D1%86%D0%B2%D0%B5%D1%82%D1%8B%D0%B1%D1%83%D0%BA%D0%B5%D1%82%D1%8B?refer=embed">#цветыбукеты</a> <a title="букет" target="_blank" href="https://www.tiktok.com/tag/%D0%B1%D1%83%D0%BA%D0%B5%D1%82?refer=embed">#букет</a> <a target="_blank" title="♬ Paris, Texas - Lana Del Rey" href="https://www.tiktok.com/music/Paris-Texas-7213167180764940289?refer=embed">♬ Paris, Texas - Lana Del Rey</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Значешь, меня так согрел когда то кружочек, где ты помоему в какой-то книжке хранишь сушеные лепестки мною подаренных цветов 🥹'
), (
    '2024-02-14',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@xxl_n_n_/video/7313262621778578731" data-video-id="7313262621778578731" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@xxl_n_n_" href="https://www.tiktok.com/@xxl_n_n_?refer=embed">@xxl_n_n_</a> <p></p> <a target="_blank" title="♬ оригинальный звук - кариночка я" href="https://www.tiktok.com/music/оригинальный-звук-7313262673787931435?refer=embed">♬ оригинальный звук - кариночка я</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Мы же будем спать вместе? 🥰'
), (
    '2024-02-15',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@memehubproduction/video/7311360805243604231" data-video-id="7311360805243604231" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@memehubproduction" href="https://www.tiktok.com/@memehubproduction?refer=embed">@memehubproduction</a> Подозрительно🤔 <a title="отношения" target="_blank" href="https://www.tiktok.com/tag/%D0%BE%D1%82%D0%BD%D0%BE%D1%88%D0%B5%D0%BD%D0%B8%D1%8F?refer=embed">#отношения</a> <a title="девушка" target="_blank" href="https://www.tiktok.com/tag/%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B0?refer=embed">#девушка</a> <a title="парень" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%B0%D1%80%D0%B5%D0%BD%D1%8C?refer=embed">#парень</a> <a title="ревность" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D1%8C?refer=embed">#ревность</a> <a title="ревнивая" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B2%D0%B0%D1%8F?refer=embed">#ревнивая</a> <a title="ревнивый" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B2%D1%8B%D0%B9?refer=embed">#ревнивый</a> <a target="_blank" title="♬ оригинальный звук - Meme_hub_Production" href="https://www.tiktok.com/music/оригинальный-звук-7311360835410004738?refer=embed">♬ оригинальный звук - Meme_hub_Production</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'А ты красишь каждый мой день! ❤️ Твои кружечки и сообщения это так важно для меня 🥺'
), (
    '2024-02-16',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@ismailovv17/video/7311423516027391234" data-video-id="7311423516027391234" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@ismailovv17" href="https://www.tiktok.com/@ismailovv17?refer=embed">@ismailovv17</a> че там? <a title="топ" target="_blank" href="https://www.tiktok.com/tag/%D1%82%D0%BE%D0%BF?refer=embed">#топ</a> <a title="снег" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D0%BD%D0%B5%D0%B3?refer=embed">#снег</a> <a target="_blank" title="♬ оригинальный звук - kankeldi" href="https://www.tiktok.com/music/оригинальный-звук-7311423587633236737?refer=embed">♬ оригинальный звук - kankeldi</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'У меня практически не бывает горячий кофе без горячей тебя 🔥'
), (
    '2024-02-17',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bazaka96/video/7311982608366226694" data-video-id="7311982608366226694" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bazaka96" href="https://www.tiktok.com/@bazaka96?refer=embed">@bazaka96</a> <p></p> <a target="_blank" title="♬ оригінальний звук - @bazaka96" href="https://www.tiktok.com/music/оригінальний-звук-7311982621285288709?refer=embed">♬ оригінальний звук - @bazaka96</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Надеюсь наша сембя будет держаться не на контитуции, а на огромноц любви ❤️'
), (
    '2024-02-18',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mqdeka/video/7311408646875909382" data-video-id="7311408646875909382" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mqdeka" href="https://www.tiktok.com/@mqdeka?refer=embed">@mqdeka</a> <p></p> <a target="_blank" title="♬ original sound - sp3d_up" href="https://www.tiktok.com/music/original-sound-7131778454072232750?refer=embed">♬ original sound - sp3d_up</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Не грусти, солнышко ☀️ твои близкие всегда рядом ❤️'
), (
    '2024-02-19',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@natalia_varakina/video/7311337928356007173" data-video-id="7311337928356007173" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@natalia_varakina" href="https://www.tiktok.com/@natalia_varakina?refer=embed">@natalia_varakina</a> <a title="тряси" target="_blank" href="https://www.tiktok.com/tag/%D1%82%D1%80%D1%8F%D1%81%D0%B8?refer=embed">#тряси</a> <a title="recomendationsforyou" target="_blank" href="https://www.tiktok.com/tag/recomendationsforyou?refer=embed">#recomendationsforyou</a> <a target="_blank" title="♬ оригинальный звук - 🧸🎀" href="https://www.tiktok.com/music/оригинальный-звук-7311337945931516677?refer=embed">♬ оригинальный звук - 🧸🎀</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Потрясем одеялом? 🤔 или под одеялом 🙈'
), (
    '2024-02-20',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@notnowak/video/7310473393671785746" data-video-id="7310473393671785746" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@notnowak" href="https://www.tiktok.com/@notnowak?refer=embed">@notnowak</a> <p>❤️Инст:ilyanowak</p> <a target="_blank" title="♬ оригинальный звук - muddytusa" href="https://www.tiktok.com/music/оригинальный-звук-6990206434394852097?refer=embed">♬ оригинальный звук - muddytusa</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Даже побриться не жалко перед встречей 😂 люблю ❤️'
), (
    '2024-02-21',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@kit_b_meshtax/video/7309510034063396101" data-video-id="7309510034063396101" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@kit_b_meshtax" href="https://www.tiktok.com/@kit_b_meshtax?refer=embed">@kit_b_meshtax</a> <a title="рекомендации" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8?refer=embed">#рекомендации</a> <a title="девушка" target="_blank" href="https://www.tiktok.com/tag/%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B0?refer=embed">#девушка</a> <a title="переписка" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%B8%D1%81%D0%BA%D0%B0?refer=embed">#переписка</a> <a title="любовь" target="_blank" href="https://www.tiktok.com/tag/%D0%BB%D1%8E%D0%B1%D0%BE%D0%B2%D1%8C?refer=embed">#любовь</a> @лиша💗 <a target="_blank" title="♬ оригінальний звук - КІТ В МЕШТАХ" href="https://www.tiktok.com/music/оригінальний-звук-7309510045629270790?refer=embed">♬ оригінальний звук - КІТ В МЕШТАХ</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Да! Я так рад, когда у тебя хорошее настроение и все дела идут в гору! Горжусь тобой, мой лисёнок! 🥰'
), (
    '2024-02-22',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@.melovin._/video/7309516661856521477" data-video-id="7309516661856521477" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@.melovin._" href="https://www.tiktok.com/@.melovin._?refer=embed">@.melovin._</a> Безумно тебя люблю ❤️🫂 <a title="_melovin_" target="_blank" href="https://www.tiktok.com/tag/_melovin_?refer=embed">#_melovin_</a> <a title="рекомендации" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8?refer=embed">#рекомендации</a> <a title="fyp" target="_blank" href="https://www.tiktok.com/tag/fyp?refer=embed">#fyp</a> <a title="fyr" target="_blank" href="https://www.tiktok.com/tag/fyr?refer=embed">#fyr</a> <a title="рекомендации❤️" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8%E2%9D%A4%EF%B8%8F?refer=embed">#рекомендации❤️</a> <a target="_blank" title="♬ im god slowed - raisin" href="https://www.tiktok.com/music/im-god-slowed-7246102450095082266?refer=embed">♬ im god slowed - raisin</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Витуся, я очень сильно тебя люблю! ❤️'
), (
    '2024-02-23',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@anutkamiha/video/7302814090555116806" data-video-id="7302814090555116806" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@anutkamiha" href="https://www.tiktok.com/@anutkamiha?refer=embed">@anutkamiha</a> 9. Сходить пофоткаться в фотобудке📸<a title="свидание" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D0%B2%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5?refer=embed">#свидание</a> <a title="идеядлясвидания" target="_blank" href="https://www.tiktok.com/tag/%D0%B8%D0%B4%D0%B5%D1%8F%D0%B4%D0%BB%D1%8F%D1%81%D0%B2%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F?refer=embed">#идеядлясвидания</a> <a title="муж" target="_blank" href="https://www.tiktok.com/tag/%D0%BC%D1%83%D0%B6?refer=embed">#муж</a> <a title="date" target="_blank" href="https://www.tiktok.com/tag/date?refer=embed">#date</a> <a target="_blank" title="♬ the night we met - Amistat" href="https://www.tiktok.com/music/the-night-we-met-7296251379545704449?refer=embed">♬ the night we met - Amistat</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'У меня с этим сайтом всё очень структурировано, поэтому я могу сказать, что это 54 день в году, а на видео 9\365 😂 Но свидений у нас будет ещё очень много! И я надеюсь, что бы наделаем ещё кучу фотографий, для семейного альбома(ов) 🥰'
), (
    '2024-02-24',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@_.lipwix/video/7281891392064982278" data-video-id="7281891392064982278" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@_.lipwix" href="https://www.tiktok.com/@_.lipwix?refer=embed">@_.lipwix</a> <p></p> <a target="_blank" title="♬ оригинальный звук - НЮША🌚🐽" href="https://www.tiktok.com/music/оригинальный-звук-7255168404611500846?refer=embed">♬ оригинальный звук - НЮША🌚🐽</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Поедем в Японию, применять наши знания, 😂'
), (
    '2024-02-25',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@prosstokater/video/7307064092068433183" data-video-id="7307064092068433183" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@prosstokater" href="https://www.tiktok.com/@prosstokater?refer=embed">@prosstokater</a> <p>Inst- shmektrsha</p> <a target="_blank" title="♬ original sound - Просто Катер" href="https://www.tiktok.com/music/original-sound-7307064130140130079?refer=embed">♬ original sound - Просто Катер</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Я пишу эти комментарии в декабре, но... если Арсюша не дарил цветы в этом году... стукни его по голове 😂'
), (
    '2024-02-26',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@asamimichaann/video/7306852618100395271" data-video-id="7306852618100395271" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@asamimichaann" href="https://www.tiktok.com/@asamimichaann?refer=embed">@asamimichaann</a> あまえんぼタイム<a title="あさみみちゃん" target="_blank" href="https://www.tiktok.com/tag/%E3%81%82%E3%81%95%E3%81%BF%E3%81%BF%E3%81%A1%E3%82%83%E3%82%93?refer=embed">#あさみみちゃん</a> <a title="あねみみちゃん" target="_blank" href="https://www.tiktok.com/tag/%E3%81%82%E3%81%AD%E3%81%BF%E3%81%BF%E3%81%A1%E3%82%83%E3%82%93?refer=embed">#あねみみちゃん</a> <a title="サイマス" target="_blank" href="https://www.tiktok.com/tag/%E3%82%B5%E3%82%A4%E3%83%9E%E3%82%B9?refer=embed">#サイマス</a> <a title="イラスト" target="_blank" href="https://www.tiktok.com/tag/%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88?refer=embed">#イラスト</a> <a title="アニメ" target="_blank" href="https://www.tiktok.com/tag/%E3%82%A2%E3%83%8B%E3%83%A1?refer=embed">#アニメ</a> <a target="_blank" title="♬ original sound - nobody sausage" href="https://www.tiktok.com/music/original-sound-7287969077484587822?refer=embed">♬ original sound - nobody sausage</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Хочешь, чтобы я тебя по утрам так гладил? 🤭'
), (
    '2024-02-27',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@gintare.ja/video/7308668486941805857" data-video-id="7308668486941805857" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@gintare.ja" href="https://www.tiktok.com/@gintare.ja?refer=embed">@gintare.ja</a> Hug me until I smell like you… <a title="mood" target="_blank" href="https://www.tiktok.com/tag/mood?refer=embed">#mood</a><a title="capcut" target="_blank" href="https://www.tiktok.com/tag/capcut?refer=embed">#CapCut</a><a title="foryou" target="_blank" href="https://www.tiktok.com/tag/foryou?refer=embed">#foryou</a><a title="foryoupage" target="_blank" href="https://www.tiktok.com/tag/foryoupage?refer=embed">#foryoupage</a><a title="kaunas" target="_blank" href="https://www.tiktok.com/tag/kaunas?refer=embed">#kaunas</a><a title="lithuania" target="_blank" href="https://www.tiktok.com/tag/lithuania?refer=embed">#lithuania</a> <a target="_blank" title="♬ original sound - Rokas Yan" href="https://www.tiktok.com/music/original-sound-7307564932650863392?refer=embed">♬ original sound - Rokas Yan</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Обнимать тебя, это такое счастье! 😍 Я обожаю тебя! ❤️'
), (
    '2024-02-28',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@world_vladimirovich/video/7306954264687938821" data-video-id="7306954264687938821" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@world_vladimirovich" href="https://www.tiktok.com/@world_vladimirovich?refer=embed">@world_vladimirovich</a> <p>Решили сделать 3D слепок рук</p> <a target="_blank" title="♬ оригинальный звук - Roman Vladimirovich" href="https://www.tiktok.com/music/оригинальный-звук-7306954477224250118?refer=embed">♬ оригинальный звук - Roman Vladimirovich</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Своего рода напоминание, что мы бы тоже хотели слепок сделать 🤔 Запишешь в задачи для бобров? ❤️'
), (
    '2024-02-29',
    '<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@mirrrorss/video/7313297700181527810" data-video-id="7313297700181527810" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@mirrrorss" href="https://www.tiktok.com/@mirrrorss?refer=embed">@mirrrorss</a> <p></p> <a target="_blank" title="♬ оригинальный звук - miriksss_w" href="https://www.tiktok.com/music/оригинальный-звук-7313297771384720129?refer=embed">♬ оригинальный звук - miriksss_w</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>',
    'Когда мы сходим знакомиться с моими бабушкой и дедушкой? 🥹'
);
