---
- hosts: localhost
  become: yes

  tasks:
    - name: 1. Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: 2. Installing MySQL server
      apt:
        pkg: default-mysql-server
        state: present
      become: yes

    - name: 3. Installing python3-mysqldb
      apt:
        pkg: python3-mysqldb
        state: present
      become: yes

    - name: 4. Starting MySQL server
      service:
        name: mysql
        enabled: true
        state: started
      become: yes

    - name: 5. Creating MySQL user
      mysql_user:
        user: "qriositiv"
        password: "admin"
        priv: "*.*:ALL,GRANT"
        host: "%"
        state: present
        login_user: root
        login_password: "zzzxxx"
      become: yes

    - name: 6. Creating a database
      mysql_db:
        name: "vadata"
        state: present
      become: yes

    - name: 7. Copy SQL files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      become: yes
      loop:
        - { src: "../Misc/InsertData.sql", dest: "InsertData.sql" }
        - { src: "../Misc/VA.sql", dest: "VA.sql" }

    - name: 8. Importing database SQL files
      mysql_db:
        login_user: "qriositiv"
        login_password: "admin"
        state: import
        name: "vadata"
        target: "{{ item }}"
        collation: utf8mb4_unicode_ci
        encoding: utf8mb4
      loop:
        - "VA.sql"
        - "InsertData.sql"

    - name: 9. Restarting MySQL server
      service:
        name: mysql
        state: restarted
      become: yes
