---
- hosts: localhost
  become: yes

  tasks:
    - name: 1. Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: 2. Installing MySQL server
      apt:
        pkg: default-mysql-server
        state: present
      become: yes

    - name: 3. Installing python3-mysqldb
      apt:
        pkg: python3-mysqldb
        state: present
      become: yes

    - name: 4. Starting MySQL server
      service:
        name: mysql
        enabled: true
        state: started
      become: yes

    - name: 5. Creating MySQL user
      mysql_user:
        user: "qriositiv"
        password: "admin"
        priv: "*.*:ALL,GRANT"
        host: "%"
        state: present
        login_user: root
        login_password: "zzzxxx"
      become: yes

    - name: 6. Creating a database
      mysql_db:
        name: "vadata"
        state: present
      become: yes

    - name: 7. Copy SQL files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      become: yes
      loop:
        - { src: "../Misc/VA.sql", dest: "VA.sql" }
        - { src: "../Misc/InsertData/01. January/InsertData.sql", dest: "January.sql" }
        - { src: "../Misc/InsertData/02. February/InsertData.sql", dest: "February.sql" }
        - { src: "../Misc/InsertData/03. March/InsertData.sql", dest: "March.sql" }
        - { src: "../Misc/InsertData/04. April/InsertData.sql", dest: "April.sql" }
        - { src: "../Misc/InsertData/05. May/InsertData.sql", dest: "May.sql" }
        - { src: "../Misc/InsertData/06. June/InsertData.sql", dest: "June.sql" }
        - { src: "../Misc/InsertData/07. July/InsertData.sql", dest: "July.sql" }
        - { src: "../Misc/InsertData/08. August/InsertData.sql", dest: "August.sql" }
        - { src: "../Misc/InsertData/09. September/InsertData.sql", dest: "September.sql" }
        - { src: "../Misc/InsertData/10. October/InsertData.sql", dest: "October.sql" }
        - { src: "../Misc/InsertData/11. November/InsertData.sql", dest: "November.sql" }
        - { src: "../Misc/InsertData/12. December/InsertData.sql", dest: "December.sql" }
        - { src: "../Misc/InsertData/X. TestData/TestData.sql", dest: "TestData.sql" }

    - name: 8. Importing database SQL files
      mysql_db:
        login_user: "qriositiv"
        login_password: "admin"
        state: import
        name: "vadata"
        target: "{{ item }}"
        collation: utf8mb4_unicode_ci
        encoding: utf8mb4
      loop:
        - "VA.sql"
        - "January.sql"
        - "February.sql"
        - "March.sql"
        - "April.sql"
        - "May.sql"
        - "June.sql"
        - "July.sql"
        - "August.sql"
        - "September.sql"
        - "October.sql"
        - "November.sql"
        - "December.sql"
        - "TestData.sql"

    - name: 9. Restarting MySQL server
      service:
        name: mysql
        state: restarted
      become: yes
