---
- hosts: webserver
    ansible_become_pass: "zzzxxx"

  tasks:
    - name: 3. Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: 4. Install Apache2
      apt:
        name: apache2
        state: present
      become: yes

    - name: 5. Install Apache PHP Module
      apt:
        name: libapache2-mod-php
        state: present
      become: yes

    - name: 6. Install MySQL support for PHP
      apt:
        name: php-mysql
        state: present
      become: yes

    - name: 7. Remove index.html file
      file:
        path: /var/www/html/index.html
        state: absent
      become: yes

    - name: 8. Copy files from repository to /var/www/html/
      copy:
        src: "{{ item.src }}"
        dest: "/var/www/html/{{ item.dest }}"
        owner: root
        group: root
      become: yes
      loop:
        - { src: "../Web/index.html", dest: "index.html" }
        - { src: "../Web/index.notFound.html", dest: "notFound.html" }

    - name: 9. Create new directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      become: yes
      with_items:
        - /var/www/html/config
        - /var/www/html/vendor
        - /var/www/html/images

    - name: 10. Replace code from repository into connect.php
      template:
        src: ../Web/config/connect.php
        dest: /var/www/html/config/connect.php
        owner: root
        group: root
      become: yes

    - name: 10. Replace code from repository into connect.php
      template:
        src: ../Web/config/redirect.php
        dest: /var/www/html/config/redirect.php
        owner: root
        group: root
      become: yes

    - name: 10. Replace code from repository into connect.php
      template:
        src: "{{ item.src }}"
        dest: "/var/www/html/images/{{ item.dest }}"
        owner: root
        group: root
      become: yes
      loop:
        - { src: "../Web/images/VA.png", dest: "VA.png" }
        - { src: "../Web/images/sad.png", dest: "sad.png" }

    - name: 13. Restart Apache2
      service:
        name: apache2
        state: restarted
      become: yes
