---
- name: Install Apache2 and PHP modules
  hosts: localhost
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP and required modules
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        # Add more PHP modules as needed

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
